server:
  port:${port:9091}
spring:
  application:
    name: eureka-client-provider
  datasourse:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ragnar123
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
